### ISSUE TITLE
Column Width on Post

### ISSUE THREAD

**Issue by mikeve** [petemolinero/divi-builder-integration#1]
Hi

Great initiative!

If I use the Page Builder on a post and set a row with 2 columns, the widths of the sections and columns are hard coded. This does not allow for the sidebar on the post so part of the second column overruns the sidebar.

http://www.merrickville-house-tour.ca/news/dummy/

Using WP 4.1 and a child of Divi 2.2.

Thanks

Mike Venables

**Comment by mikeve** [comment]
I got it to work with some css:

```
.single-post #sidebar {display:none;}
.single-post .container:before {display: none !important;}
```

But I'm sure that its not good practice to do it this way, particularly if you don't use the builder on every post.

Mike

**Comment by petemolinero** [comment]
Thanks for the heads up, Mike! Another good solution would be to simply use the full-width layout and add a right-column with the "Sidebar" Divi module to add the sidebar. It adds another small step each time you create a page, but it works well.

In an ideal world Divi would have used percentage widths instead of pixel widths :-).

**Comment by mikeve** [comment]
Peter

Thanks, but I can¹t use the full width layout. When I select to use the
Builder, that dropbox disappears.

Cheers

Mike

---

Mike Venables, P.Eng.

TriLink Technologies Group Inc.
+1 (613) 204-2413

www.trilink.aero http://www.trilink.aero

From:  petemolinero notifications@github.com
Reply-To:  petemolinero/divi-builder-integration
<reply+0044f876c7ab626f875514f99a0e47a965222f8e513762e692cf0000000110d79c419
2a169ce0345c996@reply.github.com>
Date:  Wednesday, January 21, 2015 at 11:56 AM
To:  petemolinero/divi-builder-integration
divi-builder-integration@noreply.github.com
Cc:  Mike Venables mikeve@trilink.aero
Subject:  Re: [divi-builder-integration] Column Width on Post (#1)

Thanks for the heads up, Mike! Another good solution would be to simply use
the full-width layout and add a right-column with the "Sidebar" Divi module
to add the sidebar. It adds another small step each time you create a page,
but it works well.

In an ideal world Divi would have used percentage widths instead of pixel
widths :-).

‹
Reply to this email directly or view it on GitHub
<https://github.com/petemolinero/divi-builder-integration/issues/1#issuecomm
ent-70875108> .

**Comment by mikeve** [comment]
I found that, when creating the post BEFORE selecting the Builder, select the Full Page layout, save the post and THEN select the Builder, the Full Page Layout is still respected.

**Comment by petemolinero** [comment]
Thanks for describing the solution!
