### ISSUE TITLE
Compatibility with Divi 2.4

### ISSUE THREAD

**Issue by PthPndr** [petemolinero/divi-builder-integration#4]
I realize it was just released but I was just trying to find out if you think you will be eventually updating this for Divi 2.4? Thank You.

**Comment by petemolinero** [comment]
Hey! Unfortunately my Elegant THemes subscription ended about a month ago and I didn't renew it--so I don't have access to Divi 2.4. Just watching the Divi 2.4 release video, though it looks like it now supports all post types! So, I don't think my builder is neccessary anymore!

**Comment by PthPndr** [comment]
I understand, thanks for the reply. They did a good job with the builder, it now works on posts, pages, and projects but unfortunately not for custom post types (which is where we were using it).

**Comment by petemolinero** [comment]
Hey, someone just posted this on my blog. Thought you may be interested!

```
// Use builder on custom post types
add_filter( 'et_builder_post_types', 'rbs_et_builder_post_types' );
function rbs_et_builder_post_types ($post_types) {
  $custom_post_types = array (
    'sfwd-assignment',
    'sfwd-courses',
    'sfwd-lessons',
    'sfwd-quiz',
    'sfwd-topic',
    'sfwd-certificates'
  );
  $new_post_types = array_merge($post_types, $custom_post_types);
  return $new_post_types;
}
```

I haven't tested it, but apparently CPTs are officially supported now via this filter. Let me know how you fare!

**Comment by PthPndr** [comment]
I haven't had a chance to fully test it but it definitely appears to work. I am able to load the pagebuilder on CPT's. Thanks for the heads-up!
