### ISSUE TITLE
Doesn't work with Divi 2.4.3

### ISSUE THREAD

**Issue by carlcarlsoniv** [petemolinero/divi-builder-integration#6]
Installed this plugin, selected my custom post type in the list and the "Use Page Builder" button appears while adding/editing my custom post type, but clicking it does nothing.  Divi also recently updated their page builder, so that may be why.  On pages the button is different and says "Use the Divi Builder."

Tested on Divi 2.2 and it works.

**Comment by petemolinero** [comment]
See Issue https://github.com/petemolinero/divi-builder-integration/issues/4
